name: https://comment.canitrunquarkus.org/

concurrency: prod

on:
  workflow_dispatch:

env:
  LANG: en_US.UTF-8
  BUILDER_IMAGE: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21

jobs:
  deployment:
    runs-on: ubuntu-22.04
    environment: prod
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 21
      - name: Package
        # We don't want the native executable to be built wth test profile (e.g. including superfluous test resources)
        run: >-
          ./mvnw clean verify -Pnative -Dquarkus.profile=test
          -Dquarkus.native.container-build=true
          -Dquarkus.native.builder-image=${BUILDER_IMAGE} &&
          ./mvnw package -DskipTests -Pnative
          -Dquarkus.native.container-build=true -Dquarkus.profile=prod
          -Dquarkus.native.builder-image=${BUILDER_IMAGE}
      - name: Deploy
        if: success()
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          echo "$KNOWN_HOSTS" > ~/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "$SSH_KEY"
          scp -o UserKnownHostsFile=~/known_hosts ./target/qcommenter-*-runner qcommenter@${{ secrets.SERVER_ADDRESS }}:/home/qcommenter/prod/qcommenter.deploy
          ssh -o UserKnownHostsFile=~/known_hosts qcommenter@${{ secrets.SERVER_ADDRESS }} "sudo systemctl restart comment.canitrunquarkus.org"
          echo "Version $(git describe --tags --always) should be on https://comment.canitrunquarkus.org/"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-${{ runner.os }}
          path: |
            target/surefire-reports
